apiVersion: apps/v1
kind: Deployment
metadata:
  name: picoyplaca-frontend
  labels:
    app: picoyplaca-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picoyplaca-frontend
  template:
    metadata:
      labels:
        app: picoyplaca-frontend
    spec:
      containers:
      - name: frontend
        image: mauro101/picoyplaca-frontend:f1e3945
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: picoyplaca-frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Útil si sigues usando un entorno local continuo como Minikube/Kind
  selector:
    app: picoyplaca-frontend